#!/bin/bash

# ---------------------------
#
# Common settings for all contexts.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------

export MLKC_RXPG_APP_NAME=rxpg
