#!/bin/bash

# ---------------------------
#
# Common settings for all contexts.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------

export MLKC_POSTGIS_NETWORK_NAME=rxpg_postgis_dev
export MLKC_POSTGIS_CONTAINER_NAME=rxpg_postgis_dev
